includes = []
packages = [
    "cliphist",
    "flameshot",
    "hypr",
    "rofi",
    "systemd",
    "wlogout",
    "waybar",
    "waybar_laptop",
    "wezterm",
    "alsoftrc",
    "tmux",
    "zsh",
    "mime",
    "ssh",
    "udev_dotool",
    "udev_keychron_kb",
    "misc_spotify",
    "ghostty",
]

[files]

[variables]
