includes = []
packages = [
    "cliphist",
    "flameshot",
    "hypr",
    "nvim",
    "rofi",
    "systemd",
    "waybar",
    "wezterm",
    "wlogout",
    "alsoftrc",
    "tmux",
    "zsh",
    "mime",
    "ssh",
    "wojk_ssh",
    "udev_dotool",
    "udev_keychron_kb"
]

[files]

[variables]
